import type { Metadata } from "next";
import { ThemeProvider } from "@/components/ThemeProvider";
import { Theme, ThemePanel } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import "./globals.css";
import { DarkModeSwitch } from "@/components/DarkModeSwitch";
import MainMenu from "@/components/MainMenu";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <nav className="border-b border-border">
            <div className="container mx-auto flex justify-between bg-transparent items-center  px-5 py-1">
              <h1 className=" font-bold decoration-double decoration-primary underline decora ">
                BusinessX
              </h1>
              <MainMenu />
              <DarkModeSwitch />
            </div>
          </nav>
          <div className="container mx-auto my-3 px-3 flex justify-center">
            {children}
          </div>

          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
